# SPDX-FileCopyrightText: 2021 Union
#
# SPDX-License-Identifier: CC0-1.0

###########################################################################
# Settings
###########################################################################

- arguments: [-XTypeApplications, -XRecursiveDo]

# Sometimes [Char] is okay (if it means "a sequence of characters")
- ignore: { name: Use String }

# Some 'data' records will be extended with more fields later,
# so they shouldn't be replaced with 'newtype' blindly
- ignore: { name: Use newtype instead of data }

###########################################################################
# Various stuff
###########################################################################

- warn:
    name: "Avoid 'both'"
    lhs: both
    rhs: Control.Lens.each
    note: |
      If you use 'both' on a 2-tuple and later it's accidentally
      replaced with a longer tuple, 'both' will be silently applied to only
      the *last two elements* instead of failing with a type error.
        * If you want to traverse all elements of the tuple, use 'each'.
        * If 'both' is used on 'Either' here, replace it with 'chosen'.

- warn: { lhs: either (const True) (const False), rhs: isLeft }
- warn: { lhs: either (const False) (const True), rhs: isRight }

- warn: { lhs: map fst &&& map snd, rhs: unzip }
