# SPDX-FileCopyrightText: 2021 Union
#
# SPDX-License-Identifier: CC0-1.0

appPort: 8080
database:
  poolSize: 100
  timeout: 5
  credentials: "host=localhost port=5432 user=union dbname=union"
severity: debug
