# SPDX-FileCopyrightText: 2021-2022 Union
#
# SPDX-License-Identifier: AGPL-3.0-or-later

appPort: 8080
database:
  poolSize: 100
  timeout: 5
  credentials: "host=localhost port=5432 user=union_app dbname=union_app password=union_app"
  migrations: "./migrations"
severity: debug
jwtExpire: 86400
senderPhone: "+18592975563"
