# SPDX-FileCopyrightText: 2021-2022 Union
#
# SPDX-License-Identifier: AGPL-3.0-or-later

resolver: lts-18.28

ghc-options:
  "$everything": -haddock

packages:
  - .

extra-deps:
  - ansi-terminal-0.10.3
  - co-log-0.4.0.1
  - hasql-migration-0.3.0
  - opaleye-0.9.0.0
  - rel8-1.3.0.0
  - relude-1.0.0.1
