# SPDX-FileCopyrightText: 2021 Union
#
# SPDX-License-Identifier: AGPL-3.0-or-later

resolver: lts-18.19

ghc-options:
  "$everything": -haddock

packages:
  - .

extra-deps:
  - ansi-terminal-0.10.3
  - co-log-0.4.0.1
  - conferer-yaml-1.1.0.0
  - hasql-migration-0.3.0
  - opaleye-0.8.0.1
  - rel8-1.2.1.0
