# SPDX-FileCopyrightText: 2021-2022 Union
#
# SPDX-License-Identifier: AGPL-3.0-or-later

resolver: lts-19.13

ghc-options:
  "$everything": -haddock

packages:
  - .

extra-deps:
  # Delete it completely when it gets into LTS.
  - git: https://github.com/co-log/co-log.git
    commit: 65b89152d0ae61ac99a56fbe645ed28cfacd717e
  # review this list after @co-log@ release to LTS
  - bytebuild-0.3.11.0
  - byteslice-0.2.7.0
  - bytesmith-0.3.8.0
  - chronos-1.1.4
  - co-log-core-0.3.1.0
  - contiguous-0.6.2.0
  - run-st-0.1.1.0
  - typerep-map-0.5.0.0
  - zigzag-0.0.1.0
  # Delete it when servant-auth-server will release new version
  - git: https://github.com/haskell-servant/servant.git
    commit: 3006e90126c3bed740ef2aa368586837f18b459f
    subdirs:
      - servant-auth/servant-auth-server
