name: Haskell CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    # additionally run once per week (At 00:00 on Sunday) to maintain cache
    - cron: "0 0 * * 0"

jobs:
  hlint:
    name: HLint backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Set up HLint"
        uses: rwe/actions-hlint-setup@v1
        with:
          version: "3.3.6"

      - name: "Run HLint"
        uses: rwe/actions-hlint-run@v2
        with:
          hlint-bin: hlint --hint=backend/.hlint.yaml
          path: backend/src/
          fail-on: warning

  build:
    name: Build and test backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.0.2"
          enable-stack: true
          stack-version: "latest"

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build
        run: stack build --fast --pedantic

      - name: Run tests
        run: |
          PATH=$PATH:/usr/lib/postgresql/14/bin && export PATH
          sudo systemctl start postgresql.service && pg_isready
          git -c advice.detachedHead=false clone --depth 1 --branch 3.1 \
            https://github.com/eradman/ephemeralpg.git
          cd ephemeralpg && sudo make install
          cd .. && stack test --fast
